PRAGMA foreign_keys = ON;

CREATE TABLE movies (
  id INTEGER PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('movies', 'series', 'cartoons', 'documentaries')),
  title_ru TEXT NOT NULL,
  title_en TEXT,
  description_ru TEXT,
  description_en TEXT,
  poster_path TEXT NOT NULL,
  release_year INTEGER,
  collection_order INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX movies_category_order_idx ON movies (category, collection_order);

CREATE TABLE movie_progress (
  movie_id INTEGER PRIMARY KEY REFERENCES movies(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'unwatched'
    CHECK (status IN ('unwatched', 'planned', 'watching', 'watched', 'dropped')),
  rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  is_favorite INTEGER NOT NULL DEFAULT 0 CHECK (is_favorite IN (0, 1)),
  last_watched_at TEXT,
  watch_count INTEGER NOT NULL DEFAULT 0 CHECK (watch_count >= 0),
  notes TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX movie_progress_status_idx ON movie_progress (status);
CREATE INDEX movie_progress_favorite_idx ON movie_progress (is_favorite);
CREATE INDEX movie_progress_last_watched_idx ON movie_progress (last_watched_at DESC);

CREATE TABLE watch_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
  watched_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (movie_id, watched_at)
);

CREATE INDEX watch_history_movie_date_idx ON watch_history (movie_id, watched_at DESC);

INSERT INTO movies (
  id, category, title_ru, title_en, description_ru, description_en,
  poster_path, release_year, collection_order
) VALUES
  (7, 'movies', 'Законопослушный гражданин', NULL, NULL, NULL, '/posters/7.webp', NULL, 1),
  (9, 'movies', 'Голодные игры', NULL, NULL, NULL, '/posters/9.jpg', NULL, 2),
  (10, 'movies', 'Мандарины', NULL, NULL, NULL, '/posters/10.jpg', NULL, 3),
  (11, 'movies', 'Отец солдата', NULL, NULL, NULL, '/posters/11.jpg', NULL, 4),
  (12, 'movies', 'Фокус', NULL, NULL, NULL, '/posters/12.jpg', NULL, 5),
  (13, 'movies', 'Однажды в Америке', NULL, NULL, NULL, '/posters/13.jpg', NULL, 6),
  (14, 'movies', 'Брюс Всемогущий', NULL, NULL, NULL, '/posters/14.jpg', NULL, 7),
  (16, 'movies', 'Схватка', NULL, NULL, NULL, '/posters/16.jpg', NULL, 8),
  (17, 'movies', 'Адвокат дьявола', NULL, NULL, NULL, '/posters/17.jpg', NULL, 9),
  (18, 'movies', 'Безумно влюблённый', NULL, NULL, NULL, '/posters/18.jpg', NULL, 10),
  (19, 'movies', 'Лицо со шрамом', NULL, NULL, NULL, '/posters/19.jpg', NULL, 11),
  (20, 'movies', 'Бойцовский клуб', NULL, NULL, NULL, '/posters/20.jpg', NULL, 12),
  (21, 'movies', 'Крёстный Отец 1', NULL, NULL, NULL, '/posters/21.jpg', NULL, 13),
  (22, 'movies', 'Крёстный Отец 2', NULL, NULL, NULL, '/posters/22.jpg', NULL, 14),
  (23, 'movies', 'Крёстный Отец 3', NULL, NULL, NULL, '/posters/23.jpg', NULL, 15),
  (24, 'movies', 'Укрощение строптивого', NULL, NULL, NULL, '/posters/24.jpg', NULL, 16),
  (25, 'movies', 'Блеф', NULL, NULL, NULL, '/posters/25.jpg', NULL, 17),
  (26, 'movies', 'Нокдаун', NULL, NULL, NULL, '/posters/26.jpg', NULL, 18),
  (27, 'movies', 'Гладиатор', NULL, NULL, NULL, '/posters/27.jpg', NULL, 19),
  (28, 'movies', 'Последний самурай', NULL, NULL, NULL, '/posters/28.jpg', NULL, 20),
  (29, 'movies', 'Грань будущего', NULL, NULL, NULL, '/posters/29.jpg', NULL, 21),
  (30, 'movies', 'Обливион', NULL, NULL, NULL, '/posters/30.jpg', NULL, 22),
  (32, 'movies', 'Начало', NULL, NULL, NULL, '/posters/32.jpg', NULL, 23),
  (33, 'movies', 'Интерстеллар', NULL, NULL, NULL, '/posters/33.jpg', NULL, 24),
  (34, 'movies', 'Пианист', NULL, NULL, NULL, '/posters/34.jpg', NULL, 25),
  (35, 'movies', 'Леон', NULL, NULL, NULL, '/posters/35.webp', NULL, 26),
  (37, 'movies', 'Отступники', NULL, NULL, NULL, '/posters/37.jpg', NULL, 27),
  (38, 'movies', '1 + 1', NULL, NULL, NULL, '/posters/38.jpg', NULL, 28),
  (40, 'movies', 'Шоу Трумана', NULL, NULL, NULL, '/posters/40.jpg', NULL, 29),
  (41, 'movies', '12 лет рабства', NULL, NULL, NULL, '/posters/41.jpg', NULL, 30),
  (42, 'movies', 'По соображениям совести', NULL, NULL, NULL, '/posters/42.jpg', NULL, 31),
  (43, 'movies', 'Запах женщины', NULL, NULL, NULL, '/posters/43.jpg', NULL, 32),
  (44, 'movies', 'Путь Карлито', NULL, NULL, NULL, '/posters/44.jpg', NULL, 33),
  (45, 'movies', 'Одиннадцать друзей Оушена', NULL, NULL, NULL, '/posters/45.jpg', NULL, 34),
  (46, 'movies', 'Двенадцать друзей Оушена', NULL, NULL, NULL, '/posters/46.jpg', NULL, 35),
  (47, 'movies', 'Тринадцать друзей Оушена', NULL, NULL, NULL, '/posters/47.webp', NULL, 36),
  (48, 'movies', 'Джанго освобождённый', NULL, NULL, NULL, '/posters/48.jpg', NULL, 37),
  (49, 'movies', 'Всегда говори «да»', NULL, NULL, NULL, '/posters/49.jpg', NULL, 38),
  (50, 'movies', 'Лжец, лжец', NULL, NULL, NULL, '/posters/50.jpg', NULL, 39),
  (51, 'movies', 'Эйс Вентура: Розыск домашних животных', NULL, NULL, NULL, '/posters/51.webp', NULL, 40),
  (52, 'movies', 'Пингвины мистера Поппера', NULL, NULL, NULL, '/posters/52.jpg', NULL, 41),
  (53, 'movies', 'Последний самурай', NULL, NULL, NULL, '/posters/53.jpg', NULL, 42),
  (54, 'movies', 'Гарри Поттер и философский камень', NULL, NULL, NULL, '/posters/54.jpg', NULL, 43),
  (55, 'movies', 'Гарри Поттер и Тайная комната', NULL, NULL, NULL, '/posters/55.jpg', NULL, 44),
  (56, 'movies', 'Гарри Поттер и узник Азкабана', NULL, NULL, NULL, '/posters/56.jpg', NULL, 45),
  (57, 'movies', 'Гарри Поттер и Кубок огня', NULL, NULL, NULL, '/posters/57.jpg', NULL, 46),
  (58, 'movies', 'Гарри Поттер и Орден Феникса', NULL, NULL, NULL, '/posters/58.jpg', NULL, 47),
  (59, 'movies', 'Гарри Поттер и Принц-полукровка', NULL, NULL, NULL, '/posters/59.jpg', NULL, 48),
  (60, 'movies', 'Гарри Поттер и Дары Смерти. Часть 1', NULL, NULL, NULL, '/posters/60.jpg', NULL, 49),
  (61, 'movies', 'Гарри Поттер и Дары Смерти. Часть 2', NULL, NULL, NULL, '/posters/61.jpg', NULL, 50),
  (62, 'movies', 'Каратэ-пацан', NULL, NULL, NULL, '/posters/62.jpg', NULL, 51),
  (63, 'movies', 'Час пик', NULL, NULL, NULL, '/posters/63.jpg', NULL, 52),
  (64, 'movies', 'Час пик 2', NULL, NULL, NULL, '/posters/64.jpg', NULL, 53),
  (65, 'movies', 'Час пик 3', NULL, NULL, NULL, '/posters/65.jpg', NULL, 54),
  (66, 'movies', 'Дом большой мамочки', NULL, NULL, NULL, '/posters/66.jpg', NULL, 55),
  (67, 'movies', 'Дом большой мамочки 2', NULL, NULL, NULL, '/posters/67.jpg', NULL, 56),
  (68, 'movies', 'Дом большой мамочки 3', NULL, NULL, NULL, '/posters/68.jpg', NULL, 57),
  (69, 'movies', 'Нечего терять', NULL, NULL, NULL, '/posters/69.jpg', NULL, 58),
  (70, 'movies', 'Бриллиантовый полицейский', NULL, NULL, NULL, '/posters/70.jpg', NULL, 59),
  (71, 'movies', 'Плохие парни', NULL, NULL, NULL, '/posters/71.jpg', NULL, 60),
  (72, 'movies', 'Плохие парни 2', NULL, NULL, NULL, '/posters/72.jpg', NULL, 61),
  (73, 'movies', 'Плохие парни навсегда', NULL, NULL, NULL, '/posters/73.jpg', NULL, 62),
  (74, 'movies', 'В погоне за счастьем', NULL, NULL, NULL, '/posters/74.jpg', NULL, 63),
  (75, 'movies', 'Я — легенда', NULL, NULL, NULL, '/posters/75.jpg', NULL, 64),
  (76, 'movies', 'Освобождение', NULL, NULL, NULL, '/posters/76.png', NULL, 65),
  (77, 'movies', '300 спартанцев', NULL, NULL, NULL, '/posters/77.jpg', NULL, 66),
  (78, 'movies', '300 спартанцев: Расцвет империи', NULL, NULL, NULL, '/posters/78.jpeg', NULL, 67),
  (79, 'movies', 'Мачо и ботан', NULL, NULL, NULL, '/posters/79.jpg', NULL, 68),
  (80, 'movies', 'Мачо и ботан 2', NULL, NULL, NULL, '/posters/80.jpg', NULL, 69),
  (81, 'movies', 'Астерикс и Обеликс: Миссия «Клеопатра»', NULL, NULL, NULL, '/posters/81.jpg', NULL, 70),
  (82, 'movies', 'Астерикс на Олимпийских играх', NULL, NULL, NULL, '/posters/82.jpg', NULL, 71),
  (83, 'movies', 'Астерикс и Обеликс в Британии', NULL, NULL, NULL, '/posters/83.jpg', NULL, 72),
  (84, 'movies', 'Два ствола', NULL, NULL, NULL, '/posters/84.jpg', NULL, 73),
  (85, 'movies', 'Великий уравнитель 1', NULL, NULL, NULL, '/posters/85.jpg', NULL, 74),
  (86, 'movies', 'Великий уравнитель 2', NULL, NULL, NULL, '/posters/86.jpg', NULL, 75),
  (87, 'movies', 'Великий уравнитель 3', NULL, NULL, NULL, '/posters/87.webp', NULL, 76),
  (88, 'movies', 'Книга Илая', NULL, NULL, NULL, '/posters/88.jpg', NULL, 77),
  (89, 'movies', 'Дежа вю', NULL, NULL, NULL, '/posters/89.jpg', NULL, 78),
  (90, 'movies', 'Огнеупорный', NULL, NULL, NULL, '/posters/90.jpg', NULL, 79),
  (91, 'movies', 'Побег из Шоушенка', NULL, NULL, NULL, '/posters/91.jpg', NULL, 80),
  (92, 'movies', 'Судья', NULL, NULL, NULL, '/posters/92.jpg', NULL, 81),
  (94, 'movies', 'Изменяющий время', NULL, NULL, NULL, '/posters/94.jpg', NULL, 82),
  (95, 'movies', 'Джентльмены', NULL, NULL, NULL, '/posters/95.jpg', NULL, 83),
  (96, 'movies', 'Игры разума', NULL, NULL, NULL, '/posters/96.jpg', NULL, 84),
  (97, 'movies', 'Зелёная книга', NULL, NULL, NULL, '/posters/97.jpg', NULL, 85),
  (98, 'movies', 'Остров проклятых', NULL, NULL, NULL, '/posters/98.jpg', NULL, 86),
  (99, 'movies', 'Волк с Уолл-стрит', NULL, NULL, NULL, '/posters/99.jpg', NULL, 87),
  (100, 'movies', 'Не смотрите наверх', NULL, NULL, NULL, '/posters/100.jpg', NULL, 88),
  (101, 'movies', 'К-911. Собачья работа', NULL, NULL, NULL, '/posters/101.jpg', NULL, 89),
  (102, 'movies', 'Мистер Бин', NULL, NULL, NULL, '/posters/102.jpg', NULL, 90),
  (103, 'movies', 'Агент Джонни Инглиш', NULL, NULL, NULL, '/posters/103.jpg', NULL, 91),
  (104, 'movies', 'Агент Джонни Инглиш: Перезагрузка', NULL, NULL, NULL, '/posters/104.jpg', NULL, 92),
  (105, 'movies', 'Агент Джонни Инглиш 3.0', NULL, NULL, NULL, '/posters/105.jpg', NULL, 93),
  (106, 'movies', 'Игра', NULL, NULL, NULL, '/posters/106.jpg', NULL, 94),
  (107, 'movies', 'Счастливого дня смерти', NULL, NULL, NULL, '/posters/107.jpg', NULL, 95),
  (108, 'movies', 'Корни', NULL, NULL, NULL, '/posters/108.webp', NULL, 96),
  (8, 'documentaries', 'Дом', NULL, NULL, NULL, '/posters/8.jpg', NULL, 97),
  (15, 'documentaries', 'Зима в огне', NULL, NULL, NULL, '/posters/15.jpg', NULL, 98),
  (31, 'series', 'Викинги', NULL, NULL, NULL, '/posters/31.webp', NULL, 99),
  (39, 'series', 'Бумажный дом', NULL, NULL, NULL, '/posters/39.webp', NULL, 100),
  (93, 'series', 'Падение Ордена', NULL, NULL, NULL, '/posters/93.webp', NULL, 101),
  (1, 'cartoons', 'Неисправимый Рон', NULL, NULL, NULL, '/posters/ron.jpg', NULL, 102),
  (2, 'cartoons', 'Как приручить дракона', NULL, NULL, NULL, '/posters/drakon1.jpg', NULL, 103),
  (3, 'cartoons', 'Как приручить дракона 2', NULL, NULL, NULL, '/posters/drakon2.webp', NULL, 104),
  (4, 'cartoons', 'Как приручить дракона 3', NULL, NULL, NULL, '/posters/drakon3.webp', NULL, 105),
  (5, 'cartoons', 'В поисках Немо', NULL, NULL, NULL, '/posters/nemo.jpg', NULL, 106),
  (6, 'cartoons', 'В поисках Дори', NULL, NULL, NULL, '/posters/dori.jpg', NULL, 107);
