// movies.js

export const movieList = {
    movies: [
        { id: 7, name: "Законопослушный гражданин", image: "/posters/7.webp" },
        { id: 9, name: "Голодные игры", image: "/posters/9.jpg" },
        { id: 10, name: "Мандарины", image: "/posters/10.jpg" },
        { id: 11, name: "Отец солдата", image: "/posters/11.jpg" },
        { id: 12, name: "Фокус", image: "/posters/12.jpg" },
        { id: 13, name: "Однажды в Америке", image: "/posters/13.jpg" },
        { id: 14, name: "Брюс Всемогущий", image: "/posters/14.jpg" },
        { id: 16, name: "Схватка", image: "/posters/16.jpg" },
        { id: 17, name: "Адвокат дьявола", image: "/posters/17.jpg" },
        { id: 18, name: "Безумно влюблённый", image: "/posters/18.jpg" },
        { id: 19, name: "Лицо со шрамом", image: "/posters/19.jpg" },
        { id: 20, name: "Бойцовский клуб", image: "/posters/20.jpg" },
        { id: 21, name: "Крёстный Отец 1", image: "/posters/21.jpg" },
        { id: 22, name: "Крёстный Отец 2", image: "/posters/22.jpg" },
        { id: 23, name: "Крёстный Отец 3", image: "/posters/23.jpg" },
        { id: 24, name: "Укрощение строптивого", image: "/posters/24.jpg" },
        { id: 25, name: "Блеф", image: "/posters/25.jpg" },
        { id: 26, name: "Нокдаун", image: "/posters/26.jpg" },
        { id: 27, name: "Гладиатор", image: "/posters/27.jpg" },
        { id: 28, name: "Последний самурай", image: "/posters/28.jpg" },
        { id: 29, name: "Грань будущего", image: "/posters/29.jpg" },
        { id: 30, name: "Обливион", image: "/posters/30.jpg" },
            { id: 32, name: "Начало", image: "/posters/32.jpg" },
            { id: 33, name: "Интерстеллар", image: "/posters/33.jpg" },
            { id: 34, name: "Пианист", image: "/posters/34.jpg" },
            { id: 35, name: "Леон", image: "/posters/35.webp" },
            { id: 37, name: "Отступники", image: "/posters/37.jpg" },
            { id: 38, name: "1 + 1", image: "/posters/38.jpg" },
            { id: 40, name: "Шоу Трумана", image: "/posters/40.jpg" },
            { id: 41, name: "12 лет рабства", image: "/posters/41.jpg" },
            { id: 42, name: "По соображениям совести", image: "/posters/42.jpg" },
            { id: 43, name: "Запах женщины", image: "/posters/43.jpg" },
            { id: 44, name: "Путь Карлито", image: "/posters/44.jpg" },
            { id: 45, name: "Одиннадцать друзей Оушена", image: "/posters/45.jpg" },
            { id: 46, name: "Двенадцать друзей Оушена", image: "/posters/46.jpg" },
            { id: 47, name: "Тринадцать друзей Оушена", image: "/posters/47.webp" },
            { id: 48, name: "Джанго освобождённый", image: "/posters/48.jpg" },
            { id: 49, name: "Всегда говори «да»", image: "/posters/49.jpg" },
            { id: 50, name: "Лжец, лжец", image: "/posters/50.jpg" },
            { id: 51, name: "Эйс Вентура: Розыск домашних животных", image: "/posters/51.webp" },
            { id: 52, name: "Пингвины мистера Поппера", image: "/posters/52.jpg" },
            { id: 53, name: "Последний самурай", image: "/posters/53.jpg" },
            { id: 54, name: "Гарри Поттер и философский камень", image: "/posters/54.jpg" },
            { id: 55, name: "Гарри Поттер и Тайная комната", image: "/posters/55.jpg" },
            { id: 56, name: "Гарри Поттер и узник Азкабана", image: "/posters/56.jpg" },
            { id: 57, name: "Гарри Поттер и Кубок огня", image: "/posters/57.jpg" },
            { id: 58, name: "Гарри Поттер и Орден Феникса", image: "/posters/58.jpg" },
            { id: 59, name: "Гарри Поттер и Принц-полукровка", image: "/posters/59.jpg" },
            { id: 60, name: "Гарри Поттер и Дары Смерти. Часть 1", image: "/posters/60.jpg" },
            { id: 61, name: "Гарри Поттер и Дары Смерти. Часть 2", image: "/posters/61.jpg" },
            { id: 62, name: "Каратэ-пацан", image: "/posters/62.jpg" },
            { id: 63, name: "Час пик", image: "/posters/63.jpg" },
            { id: 64, name: "Час пик 2", image: "/posters/64.jpg" },
            { id: 65, name: "Час пик 3", image: "/posters/65.jpg" },
            { id: 66, name: "Дом большой мамочки", image: "/posters/66.jpg" },
            { id: 67, name: "Дом большой мамочки 2", image: "/posters/67.jpg" },
            { id: 68, name: "Дом большой мамочки 3", image: "/posters/68.jpg" },
            { id: 69, name: "Нечего терять", image: "/posters/69.jpg" },
            { id: 70, name: "Бриллиантовый полицейский", image: "/posters/70.jpg" },
            { id: 71, name: "Плохие парни", image: "/posters/71.jpg" },
            { id: 72, name: "Плохие парни 2", image: "/posters/72.jpg" },
            { id: 73, name: "Плохие парни навсегда", image: "/posters/73.jpg" },
            { id: 74, name: "В погоне за счастьем", image: "/posters/74.jpg" },
            { id: 75, name: "Я — легенда", image: "/posters/75.jpg" },
            { id: 76, name: "Освобождение", image: "/posters/76.png" },
            { id: 77, name: "300 спартанцев", image: "/posters/77.jpg" },
            { id: 78, name: "300 спартанцев: Расцвет империи", image: "/posters/78.jpeg" },
            { id: 79, name: "Мачо и ботан", image: "/posters/79.jpg" },
            { id: 80, name: "Мачо и ботан 2", image: "/posters/80.jpg" },
            { id: 81, name: "Астерикс и Обеликс: Миссия «Клеопатра»", image: "/posters/81.jpg" },
            { id: 82, name: "Астерикс на Олимпийских играх", image: "/posters/82.jpg" },
            { id: 83, name: "Астерикс и Обеликс в Британии", image: "/posters/83.jpg" },
            { id: 84, name: "Два ствола", image: "/posters/84.jpg" },
            { id: 85, name: "Великий уравнитель 1", image: "/posters/85.jpg" },
            { id: 86, name: "Великий уравнитель 2", image: "/posters/86.jpg" },
            { id: 87, name: "Великий уравнитель 3", image: "/posters/87.webp" },
            { id: 88, name: "Книга Илая", image: "/posters/88.jpg" },
            { id: 89, name: "Дежа вю", image: "/posters/89.jpg" },
            { id: 90, name: "Огнеупорный", image: "/posters/90.jpg" },
            { id: 91, name: "Побег из Шоушенка", image: "/posters/91.jpg" },
            { id: 92, name: "Судья", image: "/posters/92.jpg" },
            { id: 94, name: "Изменяющий время", image: "/posters/94.jpg" },
            { id: 95, name: "Джентльмены", image: "/posters/95.jpg" },
            { id: 96, name: "Игры разума", image: "/posters/96.jpg" },
            { id: 97, name: "Зелёная книга", image: "/posters/97.jpg" },
            { id: 98, name: "Остров проклятых", image: "/posters/98.jpg" },
            { id: 99, name: "Волк с Уолл-стрит", image: "/posters/99.jpg" },
            { id: 100, name: "Не смотрите наверх", image: "/posters/100.jpg" },
            { id: 101, name: "К-911. Собачья работа", image: "/posters/101.jpg" },
            { id: 102, name: "Мистер Бин", image: "/posters/102.jpg" },
            { id: 103, name: "Агент Джонни Инглиш", image: "/posters/103.jpg" },
            { id: 104, name: "Агент Джонни Инглиш: Перезагрузка", image: "/posters/104.jpg" },
            { id: 105, name: "Агент Джонни Инглиш 3.0", image: "/posters/105.jpg" },
            { id: 106, name: "Игра", image: "/posters/106.jpg" },
            { id: 107, name: "Счастливого дня смерти", image: "/posters/107.jpg" },
            { id: 108, name: "Корни", image: "/posters/108.webp" },
        ],
        
    documentaries: [
        { id: 8, name: "Дом", image: "/posters/8.jpg" },
        { id: 15, name: "Зима в огне", image: "/posters/15.jpg" },
    ],
    series: [
        { id: 31, name: "Викинги", image: "/posters/31.webp" },
        { id: 39, name: "Бумажный дом", image: "/posters/39.webp" },
        { id: 93, name: "Падение Ордена", image: "/posters/93.webp" },
    ],
    cartoons: [
        { id: 1, name: "Неисправимый Рон", image: "/posters/ron.jpg" },
        { id: 2, name: "Как приручить дракона", image: "/posters/drakon1.jpg" },
        { id: 3, name: "Как приручить дракона 2", image: "/posters/drakon2.webp" },
        { id: 4, name: "Как приручить дракона 3", image: "/posters/drakon3.webp" },
        { id: 5, name: "В поисках Немо", image: "/posters/nemo.jpg" },
        { id: 6, name: "В поисках Дори", image: "/posters/dori.jpg" }
    ]
};
